services:
  postgres:
    image: postgres

    restart: always

    environment:
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=root

    volumes:
      - db-data:/var/lib/postgresql/data

    ports:
      - '5432:5432'

volumes:
  db-data:
