services:
  postgres:
    container_name: postgres
    image: postgres

    restart: always

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    volumes:
      - db-data:/var/lib/postgresql/data

    ports:
      - '5432:5432'

  server:
    container_name: server
    build:
      context: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    restart: always
    volumes:
      - .:/usr/src/app

volumes:
  db-data:
